use_frameworks!

platform :ios, '9.0'

target 'SKImageExtensionNew_Example' do
  pod 'SKImageExtensionNew', :path => '../'

  target 'SKImageExtensionNew_Tests' do
    inherit! :search_paths

    
  end
end
